<?php

declare(strict_types=1);

namespace Tests\Feature;

use PHPUnit\Framework\TestCase;
use App\Models\User;
use App\Models\Student;
use App\Services\AuthService;
use App\Middleware\AuthMiddleware;
use App\Controllers\AuthController;
use App\Core\Request;
use App\Core\Response;
use App\Core\Session;

class RandomPasswordAndForceChangeTest extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        $dotenv = \Dotenv\Dotenv::createImmutable(dirname(__DIR__, 2));
        $dotenv->safeLoad();
        new \App\Core\Database(
            $_ENV['DB_HOST'] ?? '127.0.0.1',
            $_ENV['DB_DATABASE'] ?? 'acadtrack',
            $_ENV['DB_USERNAME'] ?? 'root',
            $_ENV['DB_PASSWORD'] ?? ''
        );

        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }
    }

    protected function tearDown(): void
    {
        $_SESSION = [];
        $_POST = [];
        $_GET = [];
    }

    public function testRandomPasswordGeneration(): void
    {
        $pwd1 = User::generateRandomPassword(12);
        $pwd2 = User::generateRandomPassword(12);

        $this->assertSame(12, strlen($pwd1));
        $this->assertSame(12, strlen($pwd2));
        $this->assertNotEquals($pwd1, $pwd2, 'Subsequent random passwords must be unique');

        // Verify password contains letters and numbers
        $this->assertMatchesRegularExpression('/[a-zA-Z]/', $pwd1);
        $this->assertMatchesRegularExpression('/[0-9]/', $pwd1);
    }

    public function testStudentCreationWithAutoGeneratedPasswordAndForceChange(): void
    {
        $uniqueId = time() . '_' . rand(1000, 9999);
        $tempPassword = User::generateRandomPassword();
        $email = "test_student_{$uniqueId}@gwc.edu";

        // Create student user via Eloquent ORM
        $user = User::create([
            'first_name' => 'Random',
            'last_name' => 'Student',
            'email' => $email,
            'student_number' => "STU-{$uniqueId}",
            'password' => password_hash($tempPassword, PASSWORD_BCRYPT),
            'role' => 'Student',
            'status' => 'active',
            'force_password_change' => true,
        ]);

        $this->assertNotNull($user->id);
        $this->assertTrue((bool) $user->force_password_change);

        // Fetch fresh from database using Eloquent
        $freshUser = User::find($user->id);
        $this->assertTrue((bool) $freshUser->force_password_change, 'force_password_change must be true in database');
        $this->assertTrue(password_verify($tempPassword, $freshUser->password), 'Password hash must verify against temporary password');

        // Cleanup
        $user->delete();
    }

    public function testAuthServiceLoginAndMiddlewareEnforcement(): void
    {
        $uniqueId = time() . '_' . rand(1000, 9999);
        $tempPassword = User::generateRandomPassword();
        $email = "test_login_{$uniqueId}@gwc.edu";

        $user = User::create([
            'first_name' => 'Forced',
            'last_name' => 'Student',
            'email' => $email,
            'student_number' => "STU-{$uniqueId}",
            'password' => password_hash($tempPassword, PASSWORD_BCRYPT),
            'role' => 'Student',
            'status' => 'active',
            'force_password_change' => true,
        ]);

        $session = new Session();
        $authService = new AuthService();

        // 1. Authenticate with temporary password
        $loggedIn = $authService->login($email, $tempPassword, $session);
        $this->assertTrue($loggedIn);
        $this->assertTrue($_SESSION['user']['force_password_change'], 'Session must flag force_password_change');

        // 2. Simulate trying to access student dashboard
        $_SERVER['REQUEST_URI'] = '/student/dashboard';
        $_SERVER['SCRIPT_NAME'] = '/index.php';
        $request = new Request();
        $response = new Response();
        $middleware = new AuthMiddleware();

        $allowed = $middleware->handle($request, $response, $session);
        $this->assertFalse($allowed, 'AuthMiddleware must block access when password change is required');
        $this->assertSame(302, $response->getStatusCode());
        $this->assertNotEmpty($session->getFlash('info'));

        // 3. Trying to access /change-password should be allowed
        $_SERVER['REQUEST_URI'] = '/change-password';
        $allowedOnPasswordChange = $middleware->handle(new Request(), new Response(), $session);
        $this->assertTrue($allowedOnPasswordChange, 'Access to /change-password must be permitted');

        // 4. Perform password change using Eloquent ORM via AuthService
        $newPassword = 'NewSecretPassword2026!';
        $updated = $authService->updatePassword((int) $user->id, $newPassword);
        $this->assertTrue($updated, 'Password update must succeed');

        // Verify in database via Eloquent
        $refreshedUser = User::find($user->id);
        $this->assertFalse((bool) $refreshedUser->force_password_change, 'force_password_change must be cleared in DB');
        $this->assertTrue(password_verify($newPassword, $refreshedUser->password));

        // Update session flag as controller would
        $_SESSION['user']['force_password_change'] = false;

        // 5. Now accessing /student/dashboard must be allowed
        $_SERVER['REQUEST_URI'] = '/student/dashboard';
        $allowedAfterChange = $middleware->handle(new Request(), new Response(), $session);
        $this->assertTrue($allowedAfterChange, 'Access to dashboard must be permitted after password change');

        // Cleanup
        $user->delete();
    }

    public function testAuthControllerChangePasswordAction(): void
    {
        $uniqueId = time() . '_' . rand(1000, 9999);
        $tempPassword = User::generateRandomPassword();
        $email = "test_ctrl_{$uniqueId}@gwc.edu";

        $user = User::create([
            'first_name' => 'Controller',
            'last_name' => 'Test',
            'email' => $email,
            'student_number' => "STU-{$uniqueId}",
            'password' => password_hash($tempPassword, PASSWORD_BCRYPT),
            'role' => 'Student',
            'status' => 'active',
            'force_password_change' => true,
        ]);

        $_SESSION['user'] = [
            'id' => (int) $user->id,
            'email' => $email,
            'first_name' => 'Controller',
            'last_name' => 'Test',
            'role' => 'Student',
            'force_password_change' => true,
        ];

        $authController = new AuthController();
        $session = new Session();

        // 1. Test empty fields
        $_POST = [
            'new_password' => '',
            'confirm_password' => '',
        ];
        $authController->changePassword(new Request(), new Response(), $session);
        $this->assertTrue($_SESSION['user']['force_password_change'], 'Must remain true when fields are empty');

        // 2. Test mismatched new passwords
        $_POST = [
            'new_password' => 'ValidNewPassword123!',
            'confirm_password' => 'MismatchedPassword123!',
        ];
        $authController->changePassword(new Request(), new Response(), $session);
        $this->assertTrue($_SESSION['user']['force_password_change'], 'Must remain true on mismatched confirmation');

        // 3. Test short new password (< 8 chars)
        $_POST = [
            'new_password' => 'short',
            'confirm_password' => 'short',
        ];
        $authController->changePassword(new Request(), new Response(), $session);
        $this->assertTrue($_SESSION['user']['force_password_change'], 'Must remain true on short password');

        // 4. Test same as temporary password
        $_POST = [
            'new_password' => $tempPassword,
            'confirm_password' => $tempPassword,
        ];
        $authController->changePassword(new Request(), new Response(), $session);
        $this->assertTrue($_SESSION['user']['force_password_change'], 'Must remain true if same password is used');

        // 5. Test valid password update
        $validNewPassword = 'StrongPassword99!';
        $_POST = [
            'new_password' => $validNewPassword,
            'confirm_password' => $validNewPassword,
        ];
        $authController->changePassword(new Request(), new Response(), $session);

        // Verify session and DB
        $this->assertFalse($_SESSION['user']['force_password_change'], 'Session flag must be false after change');

        $dbUser = User::find($user->id);
        $this->assertFalse((bool) $dbUser->force_password_change, 'Database flag must be false after change');
        $this->assertTrue(password_verify($validNewPassword, $dbUser->password));

        // Cleanup
        $user->delete();
    }
}
